apiVersion: v1
kind: Service
metadata:
  name: {{ template "onlydoc.fullname" . }}
  labels:
    app: {{ template "onlydoc.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  {{- if (eq .Values.service.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.serviceExternalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - name: http
      port: 80
      targetPort: httpcontainer
  selector:
    app: {{ template "onlydoc.fullname" . }}
