name: Python shell
version: 1.0.0
appVersion: 1.0.0
description: A shell in a browser with python 3.6.
keywords:
- python
- bash
- shell
home: https://github.com/shellinabox/shellinabox
icon: https://mpng.pngfly.com/20181115/ttc/kisspng-programming-python-logo-programming-language-compu-data-analysis-course-st-hua-private-school-5bedd96a011543.8733544715423143460044.jpg
sources:
- https://github.com/shellinabox/shellinabox
- https://github.com/virtlabs/vlabs/tree/master/marketplace/pyshellinabox
maintainers:
- name: sferretti
  email: fakeemail@fake.fake

