apiVersion: v1
kind: Secret
metadata:
  name: {{ template "psiabox.fullname" . }}
  labels:
    app: {{ template "psiabox.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.password }}
  SX_P:  {{ .Values.password | b64enc | quote }}
  {{ else }}
  SX_P: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
