apiVersion: v1
kind: Service
metadata:
  name: {{ template "psiabox.fullname" . }}
  labels:
    app: {{ template "psiabox.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.serviceExternalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - name: http
      port: 80
      targetPort: http
    app: {{ template "psiabox.fullname" . }}
